### ISSUE TITLE
no SetInternal in package BigInteger after 'npm install Yaffle/Expression'

### ISSUE THREAD

**Issue by vapegod1514** [Yaffle/Expression#11]
file:///Users//WebstormProjects/ami_project/node_modules/@yaffle/expression/SmallBigInt.js:128
    globalThis.BigInteger._setInternal(BigIntWrapper);
                          ^

TypeError: Cannot read properties of undefined (reading '_setInternal')
    at file:///Users//WebstormProjects/ami_project/node_modules/@yaffle/expression/SmallBigInt.js:128:27
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)

**Comment by Yaffle** [comment]
thanks, I need to update this library, will do this soon

**Comment by Yaffle** [comment]
@vapegod1514 , sorry for the long delay, I have updated the library, please check it if you are still interesting
