### ISSUE TITLE
Module not found: Can't resolve './node_modules/quadraticsievefactorization/isPrime.js'

### ISSUE THREAD

**Issue by NJneeraj** [Yaffle/Expression#13]
I am using next-js 14 and I am getting this error..When trying to use npm run dev or npm run build
`./node_modules/@yaffle/expression/primeFactor.js
Module not found: Can't resolve './node_modules/quadraticsievefactorization/isPrime.js'`
I also looked in the node_modules directory of this library and this file does not exist . But it shows on this github repository.
I don't know why.Please fix this.

**Comment by NJneeraj** [comment]
I checked the npm package of quadraticsievefactorization and it does not have any isPrime.js file

**Comment by Yaffle** [comment]
Thank you
It was moved to https://github.com/Yaffle/PollardsRho/blob/main/isPrime.js .
I need to update the repo

**Comment by NJneeraj** [comment]
> Thank you It was moved to https://github.com/Yaffle/PollardsRho/blob/main/isPrime.js . I need to update the repo

I checked the isPrime.js file...I found it in the lib folder of quadraticsievefactorization folder.Can you tell me how much time it will take you to fix this issue ?

**Comment by Yaffle** [comment]
@NJneeraj , I have pushed a new version with the change, please look

**Comment by NJneeraj** [comment]
> @NJneeraj , I have pushed a new version with the change, please look

Thanks a lot! The issue is fixed
