### ISSUE TITLE
Complex eigen values not working

### ISSUE THREAD

**Issue by eNtrozx** [Yaffle/Expression#2]
First I would like to say that this is a great library, I have been searching for something like this for a long time.

Regarding the issue, in the demo it works fine, for example:

`var matrix = ExpressionParser.parse('{{0,1},{-1,0}}').matrix;`
`var x = Expression.getEigenvalues(matrix);`
`var eigenvalues = x.eigenvalues;`
`console.log(eigenvalues.toString()) // prints i,-i`

But when I try the exact same code in my application (browser) it seems to get stuck in a loop.

It works great for real eigen values (as I've seen so far).

version 0.0.22.

**Comment by Yaffle** [comment]
@eNtrozx , thanks, I am glad somebody has found that library :-)
You are right, complex values are not supported well, only sometimes it can find them, as well as the real values.
This lib is not so good for eigenvalues...
I will check why the same code may stuck...

**Comment by Yaffle** [comment]
I have fixed a small bug, now it should work with your example.
