### ISSUE TITLE
Jordan Decomposition is slow

### ISSUE THREAD

**Issue by EmmanuelMess** [Yaffle/Expression#3]
This code seems to take wayy too long to compute:
```js
  var matrix = ExpressionParser.parse('{{0, 2, 0}, {-1+i, 0, -1+i},{-1-i, 0, 1-i}}').matrix;

  var x = Expression.getEigenvalues(matrix);
  var multiplicities = x.multiplicities;
  var eigenvalues = x.eigenvalues;
  var eigenvectors = Expression.getEigenvectors(matrix, x.eigenvalues).eigenvectors;

  var y = Expression.getFormaDeJordan(matrix, eigenvalues, multiplicities, eigenvectors);

  var po = {useMatrixContainer: false};
  document.getElementById("output").innerHTML = "<math>" + new Expression.Matrix(matrix).toMathML(po) + "<mo>=</mo>" + new Expression.Matrix(y.P).toMathML(po) + "<mo>×</mo>" + new Expression.Matrix(y.J).toMathML(po) + "<mo>×</mo>" + new Expression.Matrix(y.P_INVERSED).toMathML(po) + "</math>";
```

**Comment by EmmanuelMess** [comment]
Flamegraph:
![a](https://user-images.githubusercontent.com/10991116/108573415-3d89ea00-72f3-11eb-8525-b31ade90f1e3.png)

Seems the eigenvalues need to be calculated faster.

[profile.zip](https://github.com/Yaffle/Expression/files/6013691/profile.zip)

**Comment by EmmanuelMess** [comment]
IMO the eigenvalue calculation should be separated into different cases, where easier cases get calculated with exact methods and other get calculated with aproximations. See a few algorithms here https://en.wikipedia.org/wiki/List_of_numerical_analysis_topics#Eigenvalue_algorithms.

**Comment by Yaffle** [comment]
@EmmanuelMess I have optimized the code for your example, but it is still slow. I am using exact methods as I don't know how to deal with the inexact values...

**Comment by EmmanuelMess** [comment]
Maybe [Faddeev–LeVerrier algorithm](https://en.wikipedia.org/wiki/Faddeev%E2%80%93LeVerrier_algorithm)'s algorithm should be implemented.

**Comment by Yaffle** [comment]
@EmmanuelMess right now it is not the slowest part, the eigenvalues can be computed for your example, but the next eigenvectors computation is very slow.

**Comment by EmmanuelMess** [comment]
[QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition) with the Gram-Schmidt method comes to mind.

**Comment by EmmanuelMess** [comment]
It seems using Givens rotations QR decomposition can be done significantly faster and be parallelized.

**Comment by Yaffle** [comment]
@EmmanuelMess I think, mathjs does it this way - library https://mathjs.org/docs/reference/functions/eigs.html or may be not.
I am not sure if I look into those algorithms soon. And are they numerical? What is the result of them: if it is a vector of numbers, then what is the accuracy of those numbers and how to represent them in the code so anybody can continue to use them?

**Comment by EmmanuelMess** [comment]
QR decomposition should be exact, if that's what you're asking. It seems math.js uses an iterative method called Jacobi though.

**Comment by EmmanuelMess** [comment]
If the largest absolute eigenvalue of a matrix (I - D^-1 * A) is less than 1 and A is invertible Jacobi converges to the solution of Ax=b. If |A||A^-1| is near 1, small changes to A or b produce small changes in x (these can be cause by errors in double precision), where |A| is the matrix norm induced by a vector norm, in particular it can be sqrt(p(A^t * A)) where p(A) is the largest absolute eigenvalue of A.

**Comment by EmmanuelMess** [comment]
[Here](https://github.com/Yaffle/Expression/files/6032713/5_1.Normas.pdf) is more info, if you know Spanish.

**Comment by Yaffle** [comment]
@EmmanuelMess , new version takes ~3 seconds for your example

**Comment by EmmanuelMess** [comment]
@Yaffle the new version is exact or inexact?

**Comment by Yaffle** [comment]
@EmmanuelMess exact
