### ISSUE TITLE
ln(-1) crashes

### ISSUE THREAD

**Issue by EmmanuelMess** [Yaffle/Expression#5]
ln(-1) = πi

**Comment by Yaffle** [comment]
this is a multivalue function, I'm a little afraid to just return "the principal value"

**Comment by EmmanuelMess** [comment]
> this is a multivalue function, I'm a little afraid to just return "the principal value"

What do you mean that ln is multivariate.

**Comment by Yaffle** [comment]
ln(-1) = πi + 2πi * k, where k is an integer

**Comment by EmmanuelMess** [comment]
> ln(-1) = πi + 2πi * k, where k is an integer

I would ignore the 2πi * k part and add a TODO.

**Comment by Yaffle** [comment]
@EmmanuelMess , ok, ln(-1) = πi in new version
