### ISSUE TITLE
Problems loading as a dynamic import

### ISSUE THREAD

**Issue by ed-puckett** [Yaffle/Expression#8]
I have created a web application that loads @yaffle/expression as a dynamic import.  I installed the code via:

    npm i @yaffle/expression

The web app loads content for the app from a local server at http://127.0.0.1:4300/.

When trying to load the @yaffle/expression code in the app from a script which is three directory levels down from node_modules:

    const { ... } = await import('../../../node_modules/@yaffle/expression/index.js')

I get the following error in the dev tools console:

    GET http://127.0.0.1:4300/node_modules/@yaffle/expression/node_modules/continuedfractionfactorization/continuedFractionFactorization.js net::ERR_ABORTED 404 (Not Found)

Note that continuedfractionfactorization is installed in the top-level node_modules directory, not one under @yaffle/expression.

# Workaround

I created a symbolic link to the main node_modules directory in the @yaffle/expression directory:

    cd node_modules/@yaffle/expression/ && ln -s ../../../node_modules .

Then everything seems to load correctly.

# Problems running usage example

The code in the Usage Example does not run.  This error occurs:

    ReferenceError: Expression is not defined at isRational (http://127.0.0.1:4300/node_modules/@yaffle/expression/PolynomialRoot.js:32:40)

When that is fixed, then this error occurs:

    ReferenceError: Polynomial is not defined at upgrade (http://127.0.0.1:4300/node_modules/@yaffle/expression/ExpressionWithPolynomialRoot.js:208:15)

To work around these issues, I added the following after the import():

    globalThis.Expression = Expression;
    globalThis.Polynomial = Polynomial;

Also, note that the ".result" must be removed from the Usage Examples code in:

    console.log(p.getZeros(5).result.map(...))

# Postscript

Thank you for creating and releasing this code.  You have obviously put a lot of good effort into it, and I am very much looking forward to using it!!

**Comment by Yaffle** [comment]
Thanks, i will look at those issues.
I am curious what is your use case 🙃

**Comment by Yaffle** [comment]
@blackguard is it true that the location of the node_modules is always the same as for @yaffle/expression ?

**Comment by Yaffle** [comment]
@blackguard now I am creating symlink automatically, at least on Windows, may be import-maps is a better solution.
