### ISSUE TITLE
Support variable names longer than 1 character

### ISSUE THREAD

**Issue by 28raining** [Yaffle/Expression#9]
Is it possible to have variable names longer than one character? Currently is it limited to [a-zA-Z] = 52 variables?
If it's too complicated for you I could use some look-up-table to map my variables to a character... 

Could you also provide a minified .js file, for those of us who don't use node. Usually it's in a dist folder.

Thank you!

**Comment by Yaffle** [comment]
It also supports `a_1`, `a_2`, ...
or `A_1`, `A_2`, ...

**Comment by Yaffle** [comment]
will it work for you?

**Comment by 28raining** [comment]
Yes that works for me
